@startuml
left to right direction
skinparam packageStyle rectangle

actor SinhVien as SV
actor GiangVien as GV

rectangle "Quản lý đồ án sinh viên" {

    usecase "Quản lý đồ án" as UC1
    usecase "Quản lý thông tin đồ án" as UC2
    usecase "Tạo đồ án" as UC3
    usecase "Theo dõi tiến độ" as UC4
    usecase "Báo cáo" as UC5
    usecase "Đánh giá báo cáo" as UC6

    UC1 --> UC2 : <<include>>
    UC1 --> UC3 : <<include>>

    SV --> UC1
    SV --> UC4
    SV --> UC5

    GV --> UC1
    GV --> UC4
    GV --> UC6
}
@enduml
