@startuml
|Giảng viên|
start

:Truy cập đồ án\ncần quản lý;
:Chọn mục quản lý\nthông tin đồ án;
|Hệ thống|
:Hiển thị cửa sổ\nquản lý thông tin đồ án;

|Giảng viên|
if (Thao tác gì?) then (Chỉnh sửa)
    :Chọn mục muốn\nchỉnh sửa;
else (Xóa)
    :Xóa đồ án;
endif

: Xác nhận;

|Hệ thống|
: Cập nhật thông tin đồ án;
stop
@enduml
