@startuml

|Giảng viên|
start

:Chọn tạo đồ án;
|Hệ thống|
:Hiển thị form tạo đồ án;

|Giảng viên|
:Nhập thông tin đồ án mới;

|Hệ thống|
:Tạo đồ án mới;
:Hiển thị thông báo thành công;

stop
@enduml
