@startuml
|Giảng viên|
start
:Giao nhiệm vụ;

|Hệ thống|
:Cập nhật danh sách nhiệm vụ;

|Sinh viên|
:Xem danh sách nhiệm vụ;
:Truy cập nhiệm vụ\ncần thực hiện;

:Nộp bài;

|Hệ thống|
:Cập nhật bài làm;

|Giảng viên|
:Đánh giá;

|Hệ thống|
:Cập nhật đánh giá;

|Sinh viên|
:Xem đánh giá;
stop
@enduml